# Generated by Django 4.0.1 on 2022-01-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_new_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_order',
            name='pincode_new_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
